# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place_of_residence', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
