# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170226_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='email_addr',
        ),
    ]
